### PR TITLE
Reciprocate Friendship DB Entries

### PR DESCRIPTION
**Pull request by pointerish**
This PR implements the following:

- Refactor `FriendshipsController#create` and `FriendshipsController#update` to create/update two DB entries per friendship.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @pointerish**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 you were requested in this milestone to create another friendship when accepting a friend request. thanks to this, you can find user friends only by user_id in friendships table.
---
### Requested 🔴 

- [ ] in the friendship model you have to declare a method the not only confirms the first friendship but also created another one with user_id and friend_id inversed.
 

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by pointerish** [comment]
Hi @mahmoud717,

I'm creating the reciprocate `Friendship` with the `FriendshipsController` when the friend request hits the `create` and/or `update` methods, could you please elaborate on why do I need to alter my `Friendship` model if I'm already successfully creating the reciprocate `Friendship`?

**Comment by mahmoud717** [comment]
You should create two-way friendships meaning that when a friendship is accepted there should be two row in the friendship table. 
For example if user1 and user2 the should be two friendships one with user_id = user1 , friend_id = user2
And anther with the opesite

**Comment by pointerish** [comment]
Thank you for your response, @mahmoud717. That's exactly what I'm doing with `FriendshipsController#create` and `FriendshipsController#update`. Also, if you check the `friendships` table you will see the two new rows that describe the Friendship.

Am I missing something else?

**Comment by mahmoud717** [comment]
Here you are only confirming the friendship not creating a new row

**Comment by mahmoud717** [comment]
And the create action you are only creating one row

**Comment by mahmoud717** [comment]
You should be creating the second friendship in the update action not in the create one

**Comment by mahmoud717** [comment]
This way if you want to decline a friendship you only have to delete one row

**Comment by pointerish** [comment]
Okay, those two last remarks are completely different from your previous stance of me not creating the second row at all which I was in fact doing. I'll work on the update and resubmit. Thanks!

**Comment by mahmoud717** [comment]
sorry for that, I didn't check my initial comment and I've mistaken you for another student.

**Comment by pointerish** [comment]
No worries, I appreciate you took the time to provide timely responses! Thanks!

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @pointerish  ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
