### PR TITLE
Add ERD diagram to newly created Docs directory

### PR DESCRIPTION
**Pull request by pointerish**
This PR implements the following:

- ERD for Friendships new table
- Newly added `docs` directory inside project's root directory

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @pointerish 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] `user_id` is missing in the `friendships` table, please update it
- [ ] Please update the relationship between tables properly
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by pointerish** [comment]
Hi TSEs

I have updated the `friendships` table to have an `user_id` FK. The following I did not understand:

> Please update the relationship between tables properly

A "friendee" is also a user and therefore its ID references a user entry.

Regards
Josias Alvarado

**Review by blackpintz — CHANGES_REQUESTED** [review]
# Status: Changes Required

## Hello team 👋,

**Great job on the milestone 👏. There is only one requirement needed.**

1). **A line connecting two tables should model the relationship between the tables. Below is an example of how the connecting lines should look like for each relationship. If the tool you used doesn't have this feature, you can use [lucid chart](https://www.lucidchart.com/pages/how-to-draw-ERD)**

lines

## Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Comment by pointerish** [comment]
Thanks for the clear explanation, @blackpintz . I appreciate it!

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @pointerish 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] You worked hard to fix the changes. The relationship has updated the tables other than the user. The user table should have the proper relationship with the other tables. You can see the following image for the hint
erd

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by mimipeshy** [comment]
### STATUS :APPROVED :partying_face: 

Hey there @pointerish :wave: :wave: good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

**Pull request merged**
